export const FEATURE_CREDIT_COST = {
  // Product Optimization & SEO
  OPTIMIZE_PRODUCT: 20,
  SEO_KEYWORD_DENSITY: 10,
  AI_IMAGE_ALT_TEXT: 10,
  SEO_TITLES_META_TAGS: 10,
  SEO_RANKING_TRACKER: 20,
  BULK_OPTIMIZATION: 50,
  SCHEDULED_REFRESH: 30,
  
  // Conversion Boosting & Sales Automation
  AI_GROWTH_INTELLIGENCE: 20,
  AB_TESTING: 10,
  UPSELL_EMAIL_RECEIPTS: 10,
  ABANDONED_CART_SMS: 5,
  AI_UPSELL_SUGGESTIONS: 30,
  DYNAMIC_SEGMENTATION: 20,
  BEHAVIORAL_TARGETING: 20,
  
  // Content & Branding
  SMART_PRODUCT_DESCRIPTION: 20,
  DYNAMIC_TEMPLATES: 10,
  CUSTOM_TEMPLATES: 15,
  MULTIMODAL_AI: 30,
  MULTI_CHANNEL_REPURPOSING: 30,
  
  // General AI Operations
  AI_GENERATION: 10,
  AI_OPTIMIZATION: 15,
  
  // AI Tool-specific credits (aligned with shared/ai-credits.ts)
  PRODUCT_SEO_FAST: 5,
  PRODUCT_SEO_COMPETITIVE: 15,
  BULK_OPTIMIZATION_PER_PRODUCT: 2,
  IMAGE_ALT_TEXT_PER_IMAGE: 1,
  DYNAMIC_TEMPLATES_TOOL: 3,
  BRAND_VOICE_TRAINING: 10,
  MULTIMODAL_AI_TOOL: 8,
  AB_TESTING_TOOL: 6,
  STRATEGY_INSIGHTS: 15,
  SMART_BULK_SUGGESTIONS_PER_PRODUCT: 2,
} as const;

export type FeatureType = keyof typeof FEATURE_CREDIT_COST;
