import { ZYRA_PLANS } from "./constants/plans";

export type Feature = 
  | "OPTIMIZE_PRODUCT"
  | "SEO_KEYWORD_DENSITY"
  | "AI_IMAGE_ALT_TEXT"
  | "SEO_TITLES_META_TAGS"
  | "SEO_RANKING_TRACKER"
  | "BULK_OPTIMIZATION"
  | "SCHEDULED_REFRESH"
  | "AI_GROWTH_INTELLIGENCE"
  | "AB_TESTING"
  | "UPSELL_EMAIL_RECEIPTS"
  | "ABANDONED_CART_SMS"
  | "AI_UPSELL_SUGGESTIONS"
  | "DYNAMIC_SEGMENTATION"
  | "BEHAVIORAL_TARGETING"
  | "SMART_PRODUCT_DESCRIPTION"
  | "DYNAMIC_TEMPLATES"
  | "BRAND_VOICE_MEMORY"
  | "CUSTOM_TEMPLATES"
  | "MULTIMODAL_AI"
  | "MULTI_CHANNEL_REPURPOSING"
  | "EMAIL_SMS_ANALYTICS"
  | "CONTENT_ROI_TRACKING"
  | "REVENUE_ATTRIBUTION"
  | "CSV_IMPORT_EXPORT"
  | "SHOPIFY_PUBLISH"
  | "ROLLBACK_BUTTON"
  | "SMART_BULK_SUGGESTIONS"
  | "ENTERPRISE_BULK_MANAGEMENT"
  | "FULL_AB_TEST_DASHBOARD"
  | "FULL_EMAIL_SMS_TRACKING"
  | "PRODUCT_MANAGEMENT_DASHBOARD"
  | "ENTERPRISE_ANALYTICS";

// Define which features are available in each plan
export const PLAN_FEATURES: Record<string, Feature[]> = {
  [ZYRA_PLANS.FREE]: [
    "OPTIMIZE_PRODUCT",
    "SEO_KEYWORD_DENSITY",
    "AI_GROWTH_INTELLIGENCE",
    "AB_TESTING",
    "SMART_PRODUCT_DESCRIPTION",
    "DYNAMIC_TEMPLATES",
    "EMAIL_SMS_ANALYTICS",
    "SHOPIFY_PUBLISH",
    "ROLLBACK_BUTTON",
  ],
  [ZYRA_PLANS.STARTER]: [
    "OPTIMIZE_PRODUCT",
    "SEO_KEYWORD_DENSITY",
    "AI_IMAGE_ALT_TEXT",
    "SEO_TITLES_META_TAGS",
    "AI_GROWTH_INTELLIGENCE",
    "AB_TESTING",
    "UPSELL_EMAIL_RECEIPTS",
    "ABANDONED_CART_SMS",
    "SMART_PRODUCT_DESCRIPTION",
    "DYNAMIC_TEMPLATES",
    "BRAND_VOICE_MEMORY",
    "EMAIL_SMS_ANALYTICS",
    "CSV_IMPORT_EXPORT",
    "SHOPIFY_PUBLISH",
    "ROLLBACK_BUTTON",
    "SMART_BULK_SUGGESTIONS",
  ],
  [ZYRA_PLANS.GROWTH]: [
    // All Starter features
    "OPTIMIZE_PRODUCT",
    "SEO_KEYWORD_DENSITY",
    "AI_IMAGE_ALT_TEXT",
    "SEO_TITLES_META_TAGS",
    "AI_GROWTH_INTELLIGENCE",
    "AB_TESTING",
    "UPSELL_EMAIL_RECEIPTS",
    "ABANDONED_CART_SMS",
    "SMART_PRODUCT_DESCRIPTION",
    "DYNAMIC_TEMPLATES",
    "BRAND_VOICE_MEMORY",
    "EMAIL_SMS_ANALYTICS",
    "CSV_IMPORT_EXPORT",
    "SHOPIFY_PUBLISH",
    "ROLLBACK_BUTTON",
    "SMART_BULK_SUGGESTIONS",
    // Growth-specific features
    "SEO_RANKING_TRACKER",
    "BULK_OPTIMIZATION",
    "SCHEDULED_REFRESH",
    "AI_UPSELL_SUGGESTIONS",
    "DYNAMIC_SEGMENTATION",
    "BEHAVIORAL_TARGETING",
    "FULL_AB_TEST_DASHBOARD",
    "CUSTOM_TEMPLATES",
    "MULTIMODAL_AI",
    "MULTI_CHANNEL_REPURPOSING",
    "FULL_EMAIL_SMS_TRACKING",
    "CONTENT_ROI_TRACKING",
    "REVENUE_ATTRIBUTION",
    "PRODUCT_MANAGEMENT_DASHBOARD",
  ],
  [ZYRA_PLANS.PRO]: [
    // All Growth features + Pro exclusives
    "OPTIMIZE_PRODUCT",
    "SEO_KEYWORD_DENSITY",
    "AI_IMAGE_ALT_TEXT",
    "SEO_TITLES_META_TAGS",
    "SEO_RANKING_TRACKER",
    "BULK_OPTIMIZATION",
    "SCHEDULED_REFRESH",
    "AI_GROWTH_INTELLIGENCE",
    "AB_TESTING",
    "UPSELL_EMAIL_RECEIPTS",
    "ABANDONED_CART_SMS",
    "AI_UPSELL_SUGGESTIONS",
    "DYNAMIC_SEGMENTATION",
    "BEHAVIORAL_TARGETING",
    "FULL_AB_TEST_DASHBOARD",
    "SMART_PRODUCT_DESCRIPTION",
    "DYNAMIC_TEMPLATES",
    "BRAND_VOICE_MEMORY",
    "CUSTOM_TEMPLATES",
    "MULTIMODAL_AI",
    "MULTI_CHANNEL_REPURPOSING",
    "EMAIL_SMS_ANALYTICS",
    "FULL_EMAIL_SMS_TRACKING",
    "CONTENT_ROI_TRACKING",
    "REVENUE_ATTRIBUTION",
    "PRODUCT_MANAGEMENT_DASHBOARD",
    "CSV_IMPORT_EXPORT",
    "SHOPIFY_PUBLISH",
    "ROLLBACK_BUTTON",
    "SMART_BULK_SUGGESTIONS",
    "ENTERPRISE_BULK_MANAGEMENT",
    "ENTERPRISE_ANALYTICS",
  ],
};

export function hasFeatureAccess(planId: string, feature: Feature): boolean {
  const planFeatures = PLAN_FEATURES[planId];
  if (!planFeatures) return false;
  return planFeatures.includes(feature);
}

export function getAvailableFeatures(planId: string): Feature[] {
  return PLAN_FEATURES[planId] || [];
}
